// COMPLETE INSTAGRAM POSTS DATA - VERIFIED FROM META BUSINESS SUITE
const instagramPosts = [
    // October 2025
    { date: "2025-10-31", type: "Story", title: "This post has no text", views: 76, reach: null, interactions: 0, likes: 0, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-10-31", type: "Carousel", title: "Нашите обедни специалитети", views: 834, reach: 143, interactions: 13, likes: 12, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-10-31", type: "Reel", title: "POV: Пастата е толкова добра", views: 6727, reach: 3450, interactions: 166, likes: 95, comments: 5, shares: 44, saves: 6, follows: 4 },
    { date: "2025-10-31", type: "Story", title: "This post has no text", views: 110, reach: null, interactions: 5, likes: 5, comments: null, shares: 0, saves: null, follows: null },

    // November 2025
    { date: "2025-11-01", type: "Reel", title: "Гладен? Решението е тук", views: 2984, reach: 2149, interactions: 79, likes: 52, comments: 0, shares: 16, saves: 1, follows: 0 },
    { date: "2025-11-01", type: "Story", title: "This post has no text", views: 107, reach: null, interactions: 4, likes: 4, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-02", type: "Reel", title: "Винтидж моменти, доставени при теб", views: 5163, reach: 4097, interactions: 70, likes: 50, comments: 1, shares: 10, saves: 0, follows: 2 },
    { date: "2025-11-02", type: "Story", title: "This post has no text", views: 116, reach: null, interactions: 8, likes: 7, comments: null, shares: 1, saves: null, follows: null },
    { date: "2025-11-03", type: "Reel", title: "Искаш ли перфектно приготвени ястия?", views: 1474, reach: 932, interactions: 24, likes: 17, comments: 0, shares: 2, saves: 0, follows: 0 },
    { date: "2025-11-03", type: "Story", title: "This post has no text", views: 120, reach: null, interactions: 4, likes: 4, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-04", type: "Reel", title: "Положението в кухнята е... напечено", views: 2890, reach: 1799, interactions: 72, likes: 47, comments: 2, shares: 10, saves: 1, follows: 2 },
    { date: "2025-11-04", type: "Story", title: "This post has no text", views: 119, reach: null, interactions: 6, likes: 6, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-05", type: "Story", title: "05.11.2025г.", views: 93, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-05", type: "Reel", title: "Той пази рецептата по-добре от държавна тайна", views: 4324, reach: 3010, interactions: 63, likes: 47, comments: 2, shares: 3, saves: 1, follows: 3 },
    { date: "2025-11-05", type: "Story", title: "This post has no text", views: 111, reach: null, interactions: 6, likes: 6, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-06", type: "Reel", title: "Нашият шеф пак направи огромна грешка", views: 1487, reach: 829, interactions: 25, likes: 16, comments: 1, shares: 2, saves: 0, follows: 1 },
    { date: "2025-11-06", type: "Story", title: "This post has no text", views: 149, reach: 104, interactions: 4, likes: 4, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-06", type: "Story", title: "This post has no text", views: 145, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-06", type: "Story", title: "Ризото със спанак и зеленчуци", views: 97, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-07", type: "Reel", title: "Когато братята от FilipovWD се съберат", views: 3829, reach: 2001, interactions: 87, likes: 69, comments: 1, shares: 8, saves: 1, follows: 1 },
    { date: "2025-11-07", type: "Story", title: "This post has no text", views: 107, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-08", type: "Reel", title: "Имаме да ви кажем нещо. Ние НЕ сме fast food", views: 1383, reach: 794, interactions: 37, likes: 27, comments: 1, shares: 1, saves: 0, follows: 3 },
    { date: "2025-11-08", type: "Story", title: "This post has no text", views: 102, reach: null, interactions: 5, likes: 5, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-09", type: "Reel", title: "Винаги се стремим да надминем очакванията", views: 1048, reach: 565, interactions: 21, likes: 14, comments: 0, shares: 2, saves: 1, follows: 0 },
    { date: "2025-11-09", type: "Story", title: "This post has no text", views: 105, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-09", type: "Story", title: "Ризото с пиле, спанак и зеленчуци", views: 68, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-10", type: "Story", title: "Кашкавал пане със зелена салатка", views: 64, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-12", type: "Story", title: "Бавно печено свинско месце с ориз", views: 70, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-13", type: "Story", title: "Пилешки шницел със зелена салатка", views: 56, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-13", type: "Story", title: "This post has no text", views: 59, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-16", type: "Reel", title: "Това ли искаш? Или искаш ТОВА?", views: 1827, reach: 1161, interactions: 37, likes: 30, comments: 0, shares: 2, saves: 0, follows: 2 },
    { date: "2025-11-16", type: "Story", title: "This post has no text", views: 146, reach: 114, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-16", type: "Story", title: "Пилешки филенца във винен сос", views: 106, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-17", type: "Reel", title: "Това място беше история... След мен", views: 1386, reach: 866, interactions: 33, likes: 26, comments: 0, shares: 2, saves: 0, follows: 1 },
    { date: "2025-11-17", type: "Story", title: "This post has no text", views: 106, reach: null, interactions: 6, likes: 6, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-17", type: "Story", title: "Пилешки филенца в доматено-босилков сос", views: 85, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-18", type: "Story", title: "Пиле Жулиен с бекон", views: 46, reach: null, interactions: 2, likes: 1, comments: null, shares: 1, saves: null, follows: null },
    { date: "2025-11-19", type: "Story", title: "Бъркани яйца с трюфел", views: 65, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-20", type: "Reel", title: "Добре дошли в Епизод 1 на Многото Вождове", views: 5439, reach: 2768, interactions: 202, likes: 141, comments: 10, shares: 36, saves: 0, follows: null, account: "filipovwd" },
    { date: "2025-11-20", type: "Story", title: "This post has no text", views: 89, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-20", type: "Story", title: "Сръбски Ущипаци", views: 75, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-21", type: "Reel", title: "Няма малки неща при нас", views: 3268, reach: 2285, interactions: 62, likes: 53, comments: 2, shares: 1, saves: 0, follows: 3 },
    { date: "2025-11-21", type: "Story", title: "This post has no text", views: 113, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-22", type: "Story", title: "Събота Печено пилешко филе", views: 88, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-22", type: "Reel", title: "Кой каза, че подстригване, паста и шоколад", views: 4552, reach: null, interactions: 134, likes: 122, comments: 4, shares: 8, saves: 0, follows: null, account: "sladkischo" },
    { date: "2025-11-22", type: "Story", title: "This post has no text", views: 117, reach: 100, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-23", type: "Story", title: "This post has no text", views: 166, reach: 133, interactions: 5, likes: 5, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-23", type: "Reel", title: "Усили звука! Този ритъм е саундтракът", views: 928, reach: 406, interactions: 21, likes: 15, comments: 0, shares: 3, saves: 0, follows: 0 },
    { date: "2025-11-23", type: "Story", title: "This post has no text", views: 162, reach: 114, interactions: 0, likes: 0, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-24", type: "Story", title: "Паста със свинско контра каре", views: 96, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-24", type: "Reel", title: "POV: Когато си гладен и чуваш само каквото ти изнася", views: 7401, reach: 4112, interactions: 192, likes: 140, comments: 2, shares: 28, saves: 5, follows: 1 },
    { date: "2025-11-24", type: "Story", title: "This post has no text", views: 98, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-24", type: "Story", title: "Бабино Руло Стефани", views: 86, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-25", type: "Reel", title: "За всички, които прекарват 20 минути в гледане на менюто", views: 929, reach: 538, interactions: 15, likes: 10, comments: 0, shares: 1, saves: 0, follows: 0 },
    { date: "2025-11-25", type: "Story", title: "This post has no text", views: 103, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-26", type: "Reel", title: "Къде си тази вечер?", views: 926, reach: 511, interactions: 23, likes: 18, comments: 0, shares: 1, saves: 0, follows: 0 },
    { date: "2025-11-26", type: "Story", title: "This post has no text", views: 109, reach: null, interactions: 4, likes: 4, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-27", type: "Story", title: "Свинска кавърмичка", views: 64, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-27", type: "Reel", title: "ИСТИНАТА В ОЧИТЕ", views: 1301, reach: 840, interactions: 32, likes: 25, comments: 1, shares: 1, saves: 0, follows: 0 },
    { date: "2025-11-27", type: "Story", title: "This post has no text", views: 78, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-28", type: "Story", title: "Кашкавал пане", views: 50, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-28", type: "Photo", title: "Плевен, готови ли сте за бляскаво посрещане на 2026?", views: 1247, reach: 422, interactions: 18, likes: 9, comments: 0, shares: 8, saves: 0, follows: 0 },
    { date: "2025-11-29", type: "Reel", title: "Има кулинарни престъпления, които просто не се прощават", views: 1505, reach: 937, interactions: 33, likes: 25, comments: 0, shares: 3, saves: 1, follows: 1 },
    { date: "2025-11-29", type: "Story", title: "This post has no text", views: 106, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-11-30", type: "Reel", title: "Ти нормален ли си да чистиш риба в 21-ви век?", views: 986, reach: 543, interactions: 31, likes: 25, comments: 0, shares: 0, saves: 0, follows: 1 },
    { date: "2025-11-30", type: "Story", title: "This post has no text", views: 96, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },

    // December 2025
    { date: "2025-12-01", type: "Story", title: "Паста с пилешко филе", views: 68, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-01", type: "Reel", title: "Където времето спира, а вкусът говори", views: 1782, reach: 1273, interactions: 55, likes: 42, comments: 0, shares: 5, saves: 0, follows: 0 },
    { date: "2025-12-01", type: "Story", title: "This post has no text", views: 78, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-02", type: "Story", title: "Свинска кавърма с картофено пюренце", views: 61, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-02", type: "Reel", title: "Ние не правим компромиси", views: 1163, reach: 806, interactions: 29, likes: 22, comments: 0, shares: 1, saves: 0, follows: 0 },
    { date: "2025-12-02", type: "Story", title: "This post has no text", views: 64, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-03", type: "Story", title: "Рибена чорба от сьомга", views: 52, reach: null, interactions: 0, likes: 0, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-03", type: "Carousel", title: "Обичаш Никулден, но мразиш миризмата на риба?", views: 523, reach: 136, interactions: 9, likes: 7, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-04", type: "Story", title: "Бистра супа от сьомга", views: 61, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-04", type: "Carousel", title: "Рецепта за справяне със студа: Вино, Уют и Vintage", views: 620, reach: 167, interactions: 17, likes: 15, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-05", type: "Story", title: "Яйца по селски", views: 64, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-05", type: "Carousel", title: "Елегантността не крещи. Тя се усеща", views: 438, reach: 99, interactions: 4, likes: 4, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-06", type: "Carousel", title: "Елегантността не крещи. Тя се усеща", views: 394, reach: 82, interactions: 4, likes: 4, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-07", type: "Carousel", title: "Класиката никога не излиза от мода", views: 564, reach: 137, interactions: 11, likes: 7, comments: 1, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-07", type: "Story", title: "Паста с Бурата, Тиквички", views: 73, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-08", type: "Reel", title: "Открий любимото си ястие в Ресторант Винтидж", views: 778, reach: 559, interactions: 6, likes: 6, comments: 0, shares: 0, saves: 0, follows: 1 },
    { date: "2025-12-08", type: "Story", title: "This post has no text", views: 78, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-08", type: "Story", title: "Домашна пилешка супа", views: 79, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-09", type: "Reel", title: "Внимание: Това видео съдържа кадри на опасно вкусно ризото", views: 2310, reach: 1499, interactions: 40, likes: 37, comments: 0, shares: 1, saves: 0, follows: 1 },
    { date: "2025-12-09", type: "Story", title: "This post has no text", views: 95, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-09", type: "Story", title: "Леща яхния с плочка сиренце", views: 74, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-10", type: "Reel", title: "Урок по италиански с Шеф Орлин", views: 1187, reach: 724, interactions: 20, likes: 17, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-10", type: "Story", title: "This post has no text", views: 83, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-11", type: "Story", title: "Гръцка Мусака", views: 70, reach: null, interactions: 0, likes: 0, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-11", type: "Reel", title: "Когато сметката дойде и братството е под въпрос", views: 1977, reach: 1227, interactions: 28, likes: 25, comments: 0, shares: 2, saves: 0, follows: 1 },
    { date: "2025-12-11", type: "Story", title: "This post has no text", views: 71, reach: null, interactions: 0, likes: 0, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-12", type: "Story", title: "Пилешки филенца в доматено-босилеков сос", views: 80, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-12", type: "Reel", title: "Вечната дилема: Ризото или ДЪРПАНО ТЕЛЕШКО", views: 901, reach: 569, interactions: 7, likes: 7, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-12", type: "Story", title: "This post has no text", views: 85, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },

    // VIRAL DAY - December 13, 2025
    { date: "2025-12-13", type: "Photo", title: "Брънч във Винтидж", views: 493, reach: 143, interactions: 4, likes: 2, comments: 0, shares: 2, saves: 0, follows: 0 },
    { date: "2025-12-13", type: "Reel", title: "🔥 ВИРАЛЕН ПИК! Търсите място за вечеря в Плевен?", views: 374780, reach: 201540, interactions: 3267, likes: 2265, comments: 8, shares: 748, saves: 161, follows: 130, viral: true },
    { date: "2025-12-13", type: "Story", title: "This post has no text", views: 149, reach: 109, interactions: 6, likes: 5, comments: null, shares: 1, saves: null, follows: null },

    { date: "2025-12-14", type: "Story", title: "This post has no text", views: 98, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-14", type: "Reel", title: "Не сме просто служители, ние сме част от интериора", views: 10699, reach: 6229, interactions: 138, likes: 95, comments: 0, shares: 33, saves: 5, follows: 2 },
    { date: "2025-12-14", type: "Story", title: "This post has no text", views: 123, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-15", type: "Story", title: "Бабин Миш-Маш", views: 111, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-15", type: "Reel", title: "Има места, през които просто минаваш", views: 4902, reach: 3666, interactions: 77, likes: 60, comments: 0, shares: 14, saves: 1, follows: 1 },
    { date: "2025-12-15", type: "Story", title: "This post has no text", views: 125, reach: 102, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-15", type: "Story", title: "This post has no text", views: 106, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-16", type: "Reel", title: "Ние не просто сервираме храна, ние предлагаме решения", views: 11866, reach: 5963, interactions: 146, likes: 94, comments: 3, shares: 38, saves: 3, follows: 0 },
    { date: "2025-12-16", type: "Story", title: "This post has no text", views: 102, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-17", type: "Story", title: "This post has no text", views: 65, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-17", type: "Reel", title: "Във Vintage Restaurant хуморът е винаги на ниво", views: 1815, reach: 967, interactions: 45, likes: 32, comments: 0, shares: 6, saves: 0, follows: 0 },
    { date: "2025-12-18", type: "Story", title: "This post has no text", views: 83, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-18", type: "Reel", title: "Някои престъпления просто не могат да бъдат подминати", views: 4129, reach: 2115, interactions: 82, likes: 64, comments: 2, shares: 3, saves: 2, follows: 0 },
    { date: "2025-12-18", type: "Story", title: "This post has no text", views: 96, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-19", type: "Story", title: "This post has no text", views: 87, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-19", type: "Reel", title: "Когато шефът каже Искам пълна зала", views: 3129, reach: 1998, interactions: 73, likes: 58, comments: 1, shares: 5, saves: 0, follows: 1 },
    { date: "2025-12-19", type: "Story", title: "This post has no text", views: 73, reach: null, interactions: 2, likes: 2, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-20", type: "Reel", title: "Професионализмът е наш приоритет", views: 1184, reach: 686, interactions: 30, likes: 19, comments: 0, shares: 5, saves: 0, follows: 0 },
    { date: "2025-12-21", type: "Reel", title: "Понякога думите са излишни", views: 3382, reach: 2225, interactions: 93, likes: 72, comments: 0, shares: 12, saves: 2, follows: 3 },
    { date: "2025-12-21", type: "Story", title: "This post has no text", views: 104, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-22", type: "Reel", title: "В Restaurant Vintage екипът ни е като семейство", views: 952, reach: 457, interactions: 23, likes: 20, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-22", type: "Story", title: "This post has no text", views: 113, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-23", type: "Story", title: "This post has no text", views: 76, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-23", type: "Carousel", title: "Обедно меню във Vintage – Вкус, който те връща обратно", views: 326, reach: 104, interactions: 2, likes: 2, comments: 0, shares: 0, saves: 0, follows: 1 },
    { date: "2025-12-23", type: "Carousel", title: "Едно последно сервиране... на време", views: 467, reach: 124, interactions: 9, likes: 8, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-24", type: "Photo", title: "Посрещнете 2026 г. във Vintage!", views: 409, reach: 162, interactions: 7, likes: 5, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-24", type: "Story", title: "This post has no text", views: 73, reach: null, interactions: 6, likes: 5, comments: null, shares: 1, saves: null, follows: null },
    { date: "2025-12-24", type: "Reel", title: "Във Vintage винаги е напечено", views: 1084, reach: 538, interactions: 25, likes: 19, comments: 0, shares: 2, saves: 0, follows: 1 },
    { date: "2025-12-24", type: "Story", title: "This post has no text", views: 89, reach: null, interactions: 4, likes: 4, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-25", type: "Reel", title: "Коледните бонуси във Vintage са незабравими", views: 829, reach: 424, interactions: 18, likes: 15, comments: 0, shares: 1, saves: 0, follows: 0 },
    { date: "2025-12-25", type: "Story", title: "This post has no text", views: 99, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-26", type: "Reel", title: "Когато шефът каже Мислете с главите си", views: 1031, reach: 571, interactions: 35, likes: 25, comments: 0, shares: 6, saves: 1, follows: 0 },
    { date: "2025-12-26", type: "Story", title: "This post has no text", views: 119, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-27", type: "Reel", title: "Класика в жанра! Управителят ще влезе точно в секундата", views: 5961, reach: 4061, interactions: 117, likes: 81, comments: 0, shares: 24, saves: 7, follows: 0 },
    { date: "2025-12-27", type: "Story", title: "This post has no text", views: 113, reach: null, interactions: 3, likes: 3, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-28", type: "Reel", title: "Тишината понякога казва повече от 1000 думи", views: 3285, reach: 2357, interactions: 60, likes: 43, comments: 0, shares: 11, saves: 4, follows: 0 },
    { date: "2025-12-28", type: "Story", title: "This post has no text", views: 104, reach: null, interactions: 1, likes: 1, comments: null, shares: 0, saves: null, follows: null },
    { date: "2025-12-29", type: "Reel", title: "Науката си е наука, кой сме ние да спорим с нея", views: 855, reach: 524, interactions: 12, likes: 9, comments: 0, shares: 0, saves: 0, follows: 0 },
    { date: "2025-12-30", type: "Reel", title: "POV: Броиш дните до 05.01", views: 26027, reach: 17556, interactions: 473, likes: 321, comments: 1, shares: 120, saves: 16, follows: 4 },
    { date: "2025-12-30", type: "Story", title: "This post has no text", views: 120, reach: null, interactions: 2, likes: 1, comments: null, shares: 0, saves: null, follows: 1 },
    { date: "2025-12-31", type: "Reel", title: "Равносметка в последния ден на годината", views: 1088, reach: 762, interactions: 55, likes: 47, comments: 1, shares: 1, saves: 1, follows: 0 }
];

// Calculate totals
const igTotals = {
    totalPosts: instagramPosts.length,
    totalReels: instagramPosts.filter(p => p.type === 'Reel').length,
    totalStories: instagramPosts.filter(p => p.type === 'Story').length,
    totalCarousels: instagramPosts.filter(p => p.type === 'Carousel').length,
    totalPhotos: instagramPosts.filter(p => p.type === 'Photo').length,
    totalViews: instagramPosts.reduce((sum, p) => sum + (p.views || 0), 0),
    totalReach: instagramPosts.filter(p => p.reach).reduce((sum, p) => sum + (p.reach || 0), 0),
    totalInteractions: instagramPosts.reduce((sum, p) => sum + (p.interactions || 0), 0),
    totalLikes: instagramPosts.reduce((sum, p) => sum + (p.likes || 0), 0),
    totalComments: instagramPosts.filter(p => p.comments !== null).reduce((sum, p) => sum + (p.comments || 0), 0),
    totalShares: instagramPosts.reduce((sum, p) => sum + (p.shares || 0), 0),
    totalSaves: instagramPosts.filter(p => p.saves !== null).reduce((sum, p) => sum + (p.saves || 0), 0),
    totalFollows: instagramPosts.filter(p => p.follows !== null).reduce((sum, p) => sum + (p.follows || 0), 0)
};

// Top posts by views
const topPostsByViews = [...instagramPosts].sort((a, b) => (b.views || 0) - (a.views || 0)).slice(0, 10);

// Export for use
if (typeof module !== 'undefined') {
    module.exports = { instagramPosts, igTotals, topPostsByViews };
}
